version: '3'

volumes:
  grafana:
    driver: local

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true