version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /root/Docker/uptime-kuma:/app/data
      
    ports:
      - 3001:3001

    restart: always
