version: '3'

volumes:
  grafana:
    driver: local

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /root/Docker/data/grafana:/var/lib/grafana
      
    restart: unless-stopped