version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3002:3000
    volumes:
      - /root/Docker/data/homepage:/app/config 