version: '3'

services:
  koel:
    image: phanan/koel
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=8ZN3RvbaH@EyzS6ZZ8C#meBDvE624N
      - DB_DATABASE=koel
    volumes:
      - /root/Docker/data/koel/music:/music
      - /root/Docker/data/koel/covers:/var/www/html/public/img/covers
      - /root/Docker/data/koel/search_index:/var/www/html/storage/search-indexes

  database:
    image: mysql/mysql-server:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=8ZN3RvbaH@EyzS6ZZ8C#meBDvE624N
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=8ZN3RvbaH@EyzS6ZZ8C#meBDvE624N

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local