version: "2.1"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    ports:
      - "32400:32400"

    volumes:
      - /root/Docker/data/plex:/config
      - /root/Docker/data/plex/TV-Shows:/TV-Shows
      - /root/Docker/data/plex/Movies:/Movies
      - /root/Docker/data/plex/Music:/Music

    restart: unless-stopped