version: "3.5"

services:
    scrypted:
        environment:
            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer SET_THIS_TO_SOME_RANDOM_TEXT
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
        image: koush/scrypted
        container_name: scrypted
        restart: unless-stopped
        network_mode: host

        volumes:
            - ./scrypted/volume:/server/volume