version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage

    ports:
      - 3000:3000
      
    volumes:
      - ./homepage-data:/app/config 

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true