version: '3'

volumes:
  portainer:
    driver: local
    
services:
  app:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - ./docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true