version: "2.1"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      
    ports:
      - "32400:32400"

    volumes:
      - ./config:/config
      - /media/TV-Shows:/TV-Shows
      - /media/Movies:/Movies

    restart: unless-stopped